"""empty message

Revision ID: 444c5f94bdf5
Revises: 55dbf26a2b08
Create Date: 2023-07-04 23:43:03.755392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444c5f94bdf5'
down_revision = '55dbf26a2b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_number', sa.String(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('street_number')

    # ### end Alembic commands ###
