"""empty message

Revision ID: 61a79dfeb9e3
Revises: 444c5f94bdf5
Create Date: 2023-07-04 23:44:09.075763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a79dfeb9e3'
down_revision = '444c5f94bdf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_name', sa.String(), nullable=False))
        batch_op.drop_column('street_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_number', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('street_name')

    # ### end Alembic commands ###
